project_name: realtime-buncombe

paths:
  static_grid: "data/static/buncombe_elev_slope_soildepth.parquet"
  rainfall_dir: "data/rain"
  predictions_dir: "predictions"
  models_dir: "models"
  latest_geojson: "predictions/latest.geojson"

crs:
  static_epsg: "EPSG:32119"

columns:
  x: x
  y: y
  elev: elevation_m
  slope: slope_deg
  soil: soil_depth_cm

features:
  # Map friendly names used in models to actual dataframe columns
  aliases: {}

  # Build once during feature prep (cast to 0/1 in code if needed)
  derived:
    Soil_Depth_Deep200_Flag: "soil_depth_cm >= 200"

  # Rainfall feature names as they exist in your daily features
  rainfall_all: [R1d, R3d, R7d, R30d, Max_Rainfall_3day, Max_Rainfall_30day]

models:
  logistic:
    path: models/model_LogReg_pipe_F2.joblib
    features: [Max_Rainfall_30day, R3d, R7d, R30d, elevation_m, slope_deg, Soil_Depth_Deep200_Flag]

  rf:
    path: models/model_RF_F2.joblib
    features: [Max_Rainfall_30day, Max_Rainfall_3day, R1d, R3d, elevation_m, slope_deg, Soil_Depth_Deep200_Flag]

  xgb:
    path: models/model_XGB_F2.joblib
    features: [Max_Rainfall_30day, Max_Rainfall_3day, R7d, R30d, elevation_m, slope_deg, Soil_Depth_Deep200_Flag]
